# Generated by Django 4.2.1 on 2023-05-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('closest_point_x', models.IntegerField()),
                ('closest_point_y', models.IntegerField()),
            ],
        ),
    ]
